# Generated by Django 5.0.3 on 2024-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
